mentionTweets/config/routes.rb
Rails.application.routes.draw do
  root 'mentions#index'
  resources :mentions do
    collection do
      get "/hold", to: "mentions#hold"
    end
  end
  resources :comments

end

mentionTweets/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :mention

  validates :text, length: { maximum: 140 }
  validates :mention_id, presence: true
end

mentionTweets/app/models/mention.rb
class Mention < ActiveRecord::Base
  has_one :comment
  validates_uniqueness_of :tweet_id
end

mentionTweets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

mentionTweets/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @mention = Mention.find(params[:mention])
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to mentions_path, notice: 'Comment was successfully created.'  }
      else
        format.html { redirect_to mentions_path, alert: 'Comment NOT created.'  }
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:text, :mention_id)
    end
end

mentionTweets/app/controllers/mentions_controller.rb
class MentionsController < ApplicationController

  def index
    @mentions = Mention.all
  end

  def hold
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["CONSUMER_KEY"]
      config.consumer_secret     = ENV["CONSUMER_SECRET"]
      config.access_token        = ENV["ACCESS_TOKEN"]
      config.access_token_secret = ENV["ACCESS_TOKEN_SECRET"]
    end
    @tweets = @client.mentions_timeline
    @tweets.each do |tweet|
      if ! Mention.exists?(:tweet_id => tweet.id)
        @url = 'http://' + tweet.user.profile_image_url.host + tweet.user.profile_image_url.path
        Mention.create(tweet_id: tweet.id, owner: tweet.user.name, text: tweet.text, image_path: @url, tweet_created_at: tweet.created_at)
      end
    end
  end
end

mentionTweets/app/helpers/application_helper.rb
module ApplicationHelper
end

mentionTweets/app/views/comments/_form.html.slim
.row.bg-primary
  .col-md-12
    h2.strong.text-white
      = 'Mention tweet by '
      small = @mention.owner
.row.well
  .col-md-1
    = image_tag( @mention.image_path)
  .col-md-11
    .col-md-10
      strong.text-info
        = @mention.owner
    .col-md-2
      = time_ago_in_words(@mention.tweet_created_at)
    .col-md-12
      = @mention.text
.row.well
  .col-md-12
    = form_for(@comment) do |f|
      .form-group
        = f.text_area :text, rows: 5, placeholder:'Your Text Here ...', class: 'form-control', id: 'inputField'
        = f.hidden_field :mention_id, value: @mention.id
        br
        = f.submit 'reply', class: 'btn btn-info fa fa-reply fa-2x'
        span.pull-right
          span.text-primary.strong
            | characters remaining :
          span.counter.strong
            |  140
= link_to 'Back', mentions_path

mentionTweets/app/views/comments/new.html.slim
= render 'form'

mentionTweets/app/views/layouts/application.html.slim
<!DOCTYPE html>
html
head
  title
    |TwitterApp
  == stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  == javascript_include_tag 'application', 'data-turbolinks-track' => true
  == csrf_meta_tags
body
  .container
    .row
      .col-md-2
      .col-md-8
        - if notice
          p.bg-success
            = notice
        - if alert
          p.bg-danger
            = alert
        == yield
      .col-md-2

mentionTweets/app/views/mentions/index.html.slim
.row.bg-primary
  .col-md-12
    h2.strong.text-white
      | Mention tweets
- @mentions.each do |mention|
    .row.well
      .col-md-1
        = image_tag( mention.image_path)
      .col-md-11
        .col-md-10
          strong.text-info
            = mention.owner
        .col-md-2
          = time_ago_in_words(mention.tweet_created_at)
        .col-md-12
          = mention.text

        - if mention.comment.nil?
          .col-md-10
          .col-md-2
            = link_to '', new_comment_path(mention: mention.id), class: 'btn btn-info fa fa-reply fa-2x'
        - else
          br
          br
          .col-md-12.bg-white
            .col-md-10
              strong.text-info
                | Me :
            .col-md-2
              = time_ago_in_words(mention.comment.created_at)
            .col-md-12
              = mention.comment.text
              br

= link_to 'Get Mention', hold_mentions_path, id: 'new_link', remote: true